### ISSUE TITLE
Are the 0.31 and 0.32 tags considered to be stable release?

### ISSUE THREAD

**Issue by micwoj92** [Johns-Q/uwm#1]
Question about https://sourceforge.net/p/uwm/code/ci/master/tree/ tags.

**Comment by Johns-Q** [comment]
All version tags should be stable. But i had a mouse button freeze bug, which is only fixed in the current untaged Version. If a version for distribution is needed, i can tag the current version.

**Comment by micwoj92** [comment]
No need to, but thanks for confirming. It was not 100% sure because these tags don't have tarballs uploaded to https://sourceforge.net/projects/uwm/files/Source/
